on:
  push:
    branches:
      - main
  pull_request:

name: build
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.8', '9.4.8', '9.6.6', '9.8.2']
        os: [ubuntu-latest]
        include:
          - ghc: '8.10.7'
            resolver: 'lts-18.28'
          - ghc: '9.0.2'
            resolver: 'lts-19.33'
          - ghc: '9.2.8'
            resolver: 'lts-20.26'
          - ghc: '9.4.8'
            resolver: 'lts-21.25'
          - ghc: '9.6.6'
            resolver: 'lts-22.28'
            coveralls: true
            stack_args: '--coverage'
          - ghc: '9.8.2'
            resolver: 'nightly-2024-07-13'
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
          cabal-update: false

      - name: Setup stack
        run: |
          stack config set system-ghc --global true
          echo "resolver: ${{ matrix.resolver }}" > stack.yaml

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('sequitur.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('sequitur.cabal') }}
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build dependencies
        run: stack build ${{ matrix.stack_args }} --test --no-run-tests --bench --no-run-benchmarks --only-dependencies

      - name: Build
        run: stack build ${{ matrix.stack_args }} --test --no-run-tests --bench --no-run-benchmarks

      - name: Test
        run: stack test ${{ matrix.stack_args }}

      - name: Create source tarball
        run: stack sdist

      - name: Coveralls
        if: matrix.coveralls
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.7.0/shc-Linux-X64.tar.bz2 | tar -xj
          ./shc --repo-token="$COVERALLS_REPO_TOKEN" sequitur sequitur-test
